import { h } from "vue";

// 游戏评价接口
export interface GameEvaluation {
  gameName: string;
  gameCategory: string[];
  gameTime: string;
  myScore: number;
  key: string;
}

// 表格列名
export const gameEvalColumns = [
  {
    title: "游戏名称",
    dataIndex: "gameName",
    key: "gameName",
    width: 250,
  },
  {
    title: "游戏分类",
    dataIndex: "gameCategory",
    key: "gameCategory",
    width: 200,
    render: (_, record) => {
      return record.gameCategory.map((category, index) =>
        h(
          "span",
          {
            key: index,
            class: "category-tag",
          },
          category,
        ),
      );
    },
  },
  {
    title: "游戏时间",
    dataIndex: "gameTime",
    key: "gameTime",
    width: 150,
    sorter: {
      compare: (a, b) => a.gameTime - b.gameTime,
      multiple: 1,
    },
  },
  {
    title: "我的评分",
    dataIndex: "myScore",
    key: "myScore",
    width: 150,
    sorter: {
      compare: (a, b) => a.myScore - b.myScore,
      multiple: 2,
    },
    render: (_, record) => {
      return h(
        "span",
        {
          class: "score-tag",
          style: {
            color:
              record.myScore >= 90
                ? "#52c41a"
                : record.myScore >= 80
                  ? "#1890ff"
                  : record.myScore >= 70
                    ? "#faad14"
                    : "#f5222d",
          },
        },
        record.myScore,
      );
    },
  },
];

// 个人游戏评价列表
export const gameEvalList: GameEvaluation[] = [
  {
    gameName: "艾尔登法环·黑夜君临",
    gameCategory: ["多人合作", "肉鸽"],
    gameTime: "885.5",
    myScore: 90,
    key: "1",
  },
  {
    gameName: "艾尔登法环",
    gameCategory: ["类魂"],
    gameTime: "196",
    myScore: 90,
    key: "2",
  },
  {
    gameName: "暖雪",
    gameCategory: ["肉鸽"],
    gameTime: "136.3",
    myScore: 80,
    key: "3",
  },
  {
    gameName: "黑暗之魂3",
    gameCategory: ["魂类"],
    gameTime: "124.8",
    myScore: 98,
    key: "4",
  },
  {
    gameName: "黑神话·悟空",
    gameCategory: ["动作"],
    gameTime: "114.8",
    myScore: 95,
    key: "5",
  },
  {
    gameName: "雀魂麻将",
    gameCategory: ["益智", "恐怖"],
    gameTime: "110.8",
    myScore: 75,
    key: "6",
  },
  {
    gameName: "剑星",
    gameCategory: ["动作"],
    gameTime: "108.5",
    myScore: 95,
    key: "7",
  },
  {
    gameName: "数独",
    gameCategory: ["益智"],
    gameTime: "67.6",
    myScore: 80,
    key: "8",
  },
  {
    gameName: "背包乱斗·福西法的宝藏",
    gameCategory: ["益智", "牌组构筑"],
    gameTime: "65.6",
    myScore: 85,
    key: "9",
  },
  {
    gameName: "逃离鸭科夫",
    gameCategory: ["平台射击"],
    gameTime: "58.5",
    myScore: 90,
    key: "10",
  },
  {
    gameName: "编程农场",
    gameCategory: ["编程"],
    gameTime: "44.7",
    myScore: 80,
    key: "11",
  },
  {
    gameName: "无限机兵",
    gameCategory: ["类魂"],
    gameTime: "33.8",
    myScore: 93,
    key: "12",
  },
  {
    gameName: "中国式相亲",
    gameCategory: ["模拟经营"],
    gameTime: "24.7",
    myScore: 85,
    key: "13",
  },
  {
    gameName: "叛逆神魂",
    gameCategory: ["牌组构筑", "Galgame"],
    gameTime: "23.9",
    myScore: 85,
    key: "14",
  },
  {
    gameName: "火山的女儿",
    gameCategory: ["模拟经营"],
    gameTime: "18.9",
    myScore: 90,
    key: "15",
  },
  {
    gameName: "苍翼·混沌效应",
    gameCategory: ["肉鸽"],
    gameTime: "18.2",
    myScore: 90,
    key: "16",
  },
  {
    gameName: "极限竞速·地平线4",
    gameCategory: ["赛车"],
    gameTime: "16.7",
    myScore: 80,
    key: "17",
  },
  {
    gameName: "明末·渊虚之羽",
    gameCategory: ["类魂"],
    gameTime: "14.9",
    myScore: 90,
    key: "18",
  },
  {
    gameName: "GTA5",
    gameCategory: ["动作"],
    gameTime: "13.9",
    myScore: 90,
    key: "19",
  },
  {
    gameName: "盛世天下·媚娘篇",
    gameCategory: ["历史", "互动影视"],
    gameTime: "13.8",
    myScore: 92,
    key: "20",
  },
  {
    gameName: "底特律·化身为人",
    gameCategory: ["互动影视"],
    gameTime: "13.2",
    myScore: 95,
    key: "21",
  },
  {
    gameName: "江山北望",
    gameCategory: ["互动影视"],
    gameTime: "13.1",
    myScore: 93,
    key: "22",
  },
  {
    gameName: "药剂工艺·炼金模拟器",
    gameCategory: ["模拟经营"],
    gameTime: "12.7",
    myScore: 85,
    key: "23",
  },
  {
    gameName: "恋爱从离别开始",
    gameCategory: ["互动影视"],
    gameTime: "11.4",
    myScore: 91,
    key: "24",
  },
  {
    gameName: "完蛋我被美女包围了2",
    gameCategory: ["互动影视"],
    gameTime: "11.1",
    myScore: 90,
    key: "25",
  },
  {
    gameName: "Balatro",
    gameCategory: ["牌组构筑"],
    gameTime: "10.9",
    myScore: 90,
    key: "26",
  },
  {
    gameName: "飞跃十三号房",
    gameCategory: ["互动影视"],
    gameTime: "10.6",
    myScore: 94,
    key: "27",
  },
  {
    gameName: "无尽星火",
    gameCategory: ["肉鸽"],
    gameTime: "10.2",
    myScore: 90,
    key: "28",
  },
  {
    gameName: "赛博朋克2077",
    gameCategory: ["动作"],
    gameTime: "10.1",
    myScore: 85,
    key: "29",
  },
  {
    gameName: "你好，我们还有场恋爱没谈",
    gameCategory: ["互动影视"],
    gameTime: "10",
    myScore: 92,
    key: "30",
  },
  {
    gameName: "我在地府打麻将",
    gameCategory: ["牌组构筑"],
    gameTime: "9.7",
    myScore: 93,
    key: "31",
  },
  {
    gameName: "Devil May Cry 4",
    gameCategory: ["动作", "高速ACT"],
    gameTime: "9.6",
    myScore: 90,
    key: "32",
  },
  {
    gameName: "美女请别影响我成仙",
    gameCategory: ["互动影视"],
    gameTime: "9.5",
    myScore: 91,
    key: "33",
  },
  {
    gameName: "疑案追声",
    gameCategory: ["益智", "解谜"],
    gameTime: "8.9",
    myScore: 82,
    key: "34",
  },
  {
    gameName: "美女请别影响我学习",
    gameCategory: ["互动影视"],
    gameTime: "8.6",
    myScore: 95,
    key: "35",
  },
  {
    gameName: "情感反炸模拟器",
    gameCategory: ["互动影视"],
    gameTime: "8.2",
    myScore: 91,
    key: "36",
  },
  {
    gameName: "甜心AI追捕计划",
    gameCategory: ["互动影视"],
    gameTime: "8.2",
    myScore: 85,
    key: "37",
  },
  {
    gameName: "There is no game",
    gameCategory: ["解谜"],
    gameTime: "8",
    myScore: 95,
    key: "38",
  },
  {
    gameName: "我的同事不对劲",
    gameCategory: ["互动影视"],
    gameTime: "7.7",
    myScore: 83,
    key: "39",
  },
  {
    gameName: "荒岛求生: 逃出美女岛",
    gameCategory: ["互动影视"],
    gameTime: "7.4",
    myScore: 70,
    key: "40",
  },
  {
    gameName: "咸鱼殿下",
    gameCategory: ["互动影视"],
    gameTime: "7.3",
    myScore: 92,
    key: "41",
  },
  {
    gameName: "阿西,美女室友竟然...",
    gameCategory: ["互动影视"],
    gameTime: "6.8",
    myScore: 91,
    key: "42",
  },
  {
    gameName: "心动恋旅: 樱花篇",
    gameCategory: ["互动影视"],
    gameTime: "6.3",
    myScore: 91,
    key: "43",
  },
  {
    gameName: "恶魔轮盘",
    gameCategory: ["益智", "牌组构筑"],
    gameTime: "6.2",
    myScore: 92,
    key: "44",
  },
  {
    gameName: "泡芙爱情故事",
    gameCategory: ["Galgame"],
    gameTime: "5.7",
    myScore: 90,
    key: "45",
  },
  {
    gameName: "The Room",
    gameCategory: ["解谜"],
    gameTime: "5.4",
    myScore: 80,
    key: "46",
  },
  {
    gameName: "心跳大冒险: 泰遇",
    gameCategory: ["互动影视"],
    gameTime: "4.7",
    myScore: 85,
    key: "47",
  },
  {
    gameName: "月影魅像·解放之羽",
    gameCategory: ["Galgame", "色情内容"],
    gameTime: "4.6",
    myScore: 85,
    key: "48",
  },
  {
    gameName: "禁忌试炼",
    gameCategory: ["肉鸽", "色情内容"],
    gameTime: "3.8",
    myScore: 80,
    key: "49",
  },
  {
    gameName: "The Room Two",
    gameCategory: ["解谜"],
    gameTime: "3.6",
    myScore: 80,
    key: "50",
  },
  {
    gameName: "缺氧",
    gameCategory: ["生存", "模拟经营"],
    gameTime: "3.4",
    myScore: 70,
    key: "51",
  },
  {
    gameName: "心流小筑",
    gameCategory: ["工具"],
    gameTime: "3",
    myScore: 70,
    key: "52",
  },
  {
    gameName: "米塔Miside",
    gameCategory: ["恐怖", "解谜"],
    gameTime: "2.9",
    myScore: 85,
    key: "53",
  },
  {
    gameName: "城镇叠叠乐",
    gameCategory: ["休闲"],
    gameTime: "2.8",
    myScore: 70,
    key: "54",
  },
  {
    gameName: "三伏",
    gameCategory: ["恐怖", "视觉小说"],
    gameTime: "2.8",
    myScore: 80,
    key: "55",
  },
  {
    gameName: "Delete",
    gameCategory: ["益智"],
    gameTime: "2.6",
    myScore: 85,
    key: "56",
  },
  {
    gameName: "饥荒联机版",
    gameCategory: ["生存"],
    gameTime: "2.5",
    myScore: 70,
    key: "57",
  },
  {
    gameName: "房产达人",
    gameCategory: ["模拟经营"],
    gameTime: "2.3",
    myScore: 80,
    key: "58",
  },
  {
    gameName: "只狼·影逝二度",
    gameCategory: ["类魂", "武士"],
    gameTime: "1.66",
    myScore: 0,
    key: "59",
  },
  {
    gameName: "求生之路4",
    gameCategory: ["第一人称射击"],
    gameTime: "1.6",
    myScore: 0,
    key: "60",
  },
  {
    gameName: "地狱之刃",
    gameCategory: ["动作", "ASMR"],
    gameTime: "1.55",
    myScore: 0,
    key: "61",
  },
  {
    gameName: "千恋万花",
    gameCategory: ["Galgame"],
    gameTime: "1.53",
    myScore: 0,
    key: "62",
  },
  {
    gameName: "土豆兄弟",
    gameCategory: ["肉鸽"],
    gameTime: "1.53",
    myScore: 0,
    key: "63",
  },
  {
    gameName: "Waves2",
    gameCategory: ["弹幕射击"],
    gameTime: "1.4",
    myScore: 0,
    key: "64",
  },
  {
    gameName: "纪念碑谷",
    gameCategory: ["解谜"],
    gameTime: "1",
    myScore: 0,
    key: "65",
  },
  {
    gameName: "异形工厂",
    gameCategory: ["益智"],
    gameTime: "1.0",
    myScore: 0,
    key: "66",
  },
  {
    gameName: "幻兽帕鲁",
    gameCategory: ["生存", "建造"],
    gameTime: "1.0",
    myScore: 0,
    key: "67",
  },
  {
    gameName: "空洞骑士",
    gameCategory: ["类银河恶魔城"],
    gameTime: "0.93",
    myScore: 0,
    key: "68",
  },
  {
    gameName: "深海迷航",
    gameCategory: ["Galgame"],
    gameTime: "0.75",
    myScore: 0,
    key: "69",
  },
  {
    gameName: "深岩银河",
    gameCategory: ["Galgame"],
    gameTime: "0.6",
    myScore: 0,
    key: "70",
  },
  {
    gameName: "Nunholy",
    gameCategory: ["肉鸽", "色情内容"],
    gameTime: "0.5",
    myScore: 0,
    key: "71",
  },
  {
    gameName: "你好，我们还有场恋爱没谈",
    gameCategory: ["互动影视"],
    gameTime: "0.5",
    myScore: 0,
    key: "72",
  },
  {
    gameName: "Oozi",
    gameCategory: ["平台射击"],
    gameTime: "0.5",
    myScore: 0,
    key: "73",
  },
  {
    gameName: "星露谷物语",
    gameCategory: ["模拟经营"],
    gameTime: "0.5",
    myScore: 0,
    key: "74",
  },
  {
    gameName: "Mush Dash",
    gameCategory: ["音游"],
    gameTime: "0.5",
    myScore: 0,
    key: "75",
  },
  {
    gameName: "杀戮尖塔",
    gameCategory: ["肉鸽", "牌组构筑"],
    gameTime: "0",
    myScore: 0,
    key: "76",
  },
  {
    gameName: "以撒的结合",
    gameCategory: ["平台射击"],
    gameTime: "0",
    myScore: 0,
    key: "77",
  },
  {
    gameName: "无人深空",
    gameCategory: ["生存"],
    gameTime: "0",
    myScore: 0,
    key: "78",
  },
  {
    gameName: "巫师三·狂猎",
    gameCategory: ["动作"],
    gameTime: "0",
    myScore: 0,
    key: "79",
  },
  {
    gameName: "微光之境",
    gameCategory: ["类银河恶魔城"],
    gameTime: "0",
    myScore: 0,
    key: "80",
  },
  {
    gameName: "潜水员戴夫",
    gameCategory: ["模拟经营"],
    gameTime: "0",
    myScore: 0,
    key: "81",
  },
  {
    gameName: "明末·饿殍千里行",
    gameCategory: ["视觉小说"],
    gameTime: "0",
    myScore: 0,
    key: "82",
  },
  {
    gameName: "离去之前",
    gameCategory: ["生存"],
    gameTime: "0",
    myScore: 0,
    key: "83",
  },
  {
    gameName: "Devil May Cry 5",
    gameCategory: ["高速ACT"],
    gameTime: "0",
    myScore: 0,
    key: "84",
  },
  {
    gameName: "黑暗之魂1",
    gameCategory: ["魂类"],
    gameTime: "0",
    myScore: 0,
    key: "85",
  },
  {
    gameName: "黑暗之魂2",
    gameCategory: ["魂类"],
    gameTime: "0",
    myScore: 0,
    key: "86",
  },
  {
    gameName: "暗黑地牢",
    gameCategory: ["牌组构筑"],
    gameTime: "0",
    myScore: 0,
    key: "87",
  },
  {
    gameName: "神界原罪",
    gameCategory: ["RPG"],
    gameTime: "0",
    myScore: 0,
    key: "88",
  },
  {
    gameName: "神界原罪2",
    gameCategory: ["RPG"],
    gameTime: "0",
    myScore: 0,
    key: "89",
  },
  {
    gameName: "逆转裁判",
    gameCategory: ["视觉小说"],
    gameTime: "0",
    myScore: 0,
    key: "90",
  },
  {
    gameName: "RIDE4",
    gameCategory: ["赛车"],
    gameTime: "0",
    myScore: 0,
    key: "91",
  },
  {
    gameName: "荒野大镖客2",
    gameCategory: ["动作"],
    gameTime: "0",
    myScore: 0,
    key: "92",
  },
  {
    gameName: "灵魂摆渡人",
    gameCategory: ["视觉小说"],
    gameTime: "0",
    myScore: 0,
    key: "93",
  },
  {
    gameName: "上古卷轴5",
    gameCategory: ["动作"],
    gameTime: "0",
    myScore: 0,
    key: "94",
  },
  {
    gameName: "ViewFinder",
    gameCategory: ["解谜"],
    gameTime: "0",
    myScore: 0,
    key: "95",
  },
  {
    gameName: "隐形守护者",
    gameCategory: ["互动影视", "视觉小说"],
    gameTime: "0",
    myScore: 0,
    key: "96",
  },
  {
    gameName: "嗜血印",
    gameCategory: ["动作"],
    gameTime: "0",
    myScore: 0,
    key: "97",
  },
  {
    gameName: "孤帆远航",
    gameCategory: ["无分类"],
    gameTime: "0",
    myScore: 0,
    key: "98",
  },
  {
    gameName: "不双修就去世",
    gameCategory: ["色情内容", "视觉小说"],
    gameTime: "13.5",
    myScore: 0,
    key: "99",
  },
  {
    gameName: "夏日狂想曲",
    gameCategory: ["色情内容", "视觉小说"],
    gameTime: "0",
    myScore: 0,
    key: "100",
  },
  {
    gameName: "冬日狂想曲",
    gameCategory: ["色情内容", "视觉小说"],
    gameTime: "0",
    myScore: 0,
    key: "101",
  },
  {
    gameName: "Wallpaper Engine",
    gameCategory: ["工具"],
    gameTime: "939.4",
    myScore: 100,
    key: "102",
  },
];
